[package]
name = "discordrpc"
version = "0.1.0"
description = "Manage Discord Rich Presence without the developer portal"
license = "MIT"
edition = "2021"
rust-version = "1.77"

[lib]
name = "discordrpc_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-dialog = "2"
tauri-plugin-process = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = { version = "0.37", default-features = false, features = ["system"] }
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
uuid = { version = "1", features = ["v4"] }
ureq = { version = "2", features = ["json"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_Pipes", "Win32_Foundation", "Win32_System_Threading"] }
windows = { version = "0.61", features = ["Media_Control", "Foundation", "Win32_System_Com"] }

[target.'cfg(target_os = "linux")'.dependencies]
mpris = "2"

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
panic = "abort"
strip = true
